import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, NavLink, useLocation, useNavigate} from 'react-router-dom';
import {Activity, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, LayoutDashboard, Menu, MoreHorizontal, Plus, Search, Stethoscope, Users, X, Trash2, Edit3, Bell, HeartPulse, LogOut, UserRound, ClipboardList, TrendingUp} from 'lucide-react';
import {BarChart, Bar, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, PieChart, Pie, Cell} from 'recharts';
import './styles.css';

const seedDoctors=[
 {id:'d1',name:'Dr. Ananya Rao',specialty:'General Medicine',room:'101',fee:500,days:['Mon','Tue','Thu','Fri'],color:'#4f46e5'},
 {id:'d2',name:'Dr. Vikram Reddy',specialty:'Cardiology',room:'203',fee:800,days:['Mon','Wed','Fri'],color:'#0f766e'},
 {id:'d3',name:'Dr. Meera Shah',specialty:'Dermatology',room:'105',fee:650,days:['Tue','Wed','Sat'],color:'#b45309'},
 {id:'d4',name:'Dr. Rahul Kumar',specialty:'Pediatrics',room:'112',fee:450,days:['Mon','Tue','Thu','Sat'],color:'#be185d'}
];
const seedPatients=[
 {id:'p1',name:'Arjun Kumar',phone:'9876543210',age:28,gender:'Male',lastVisit:'2026-10-02'},
 {id:'p2',name:'Sneha Reddy',phone:'9848012345',age:34,gender:'Female',lastVisit:'2026-10-01'},
 {id:'p3',name:'Rohit Sharma',phone:'9988776655',age:41,gender:'Male',lastVisit:'2026-09-27'},
 {id:'p4',name:'Lakshmi Devi',phone:'9123456780',age:52,gender:'Female',lastVisit:'2026-09-29'},
 {id:'p5',name:'Kiran Teja',phone:'9000011112',age:19,gender:'Male',lastVisit:'2026-09-25'}
];
const today='2026-10-05';
const seedAppointments=[
 {id:'a1',patientId:'p1',doctorId:'d1',date:today,time:'09:00',reason:'Routine consultation',status:'Completed'},
 {id:'a2',patientId:'p2',doctorId:'d2',date:today,time:'10:30',reason:'Follow-up',status:'Confirmed'},
 {id:'a3',patientId:'p3',doctorId:'d3',date:today,time:'11:30',reason:'Skin consultation',status:'Confirmed'},
 {id:'a4',patientId:'p4',doctorId:'d1',date:today,time:'14:00',reason:'Blood pressure review',status:'Scheduled'},
 {id:'a5',patientId:'p5',doctorId:'d4',date:today,time:'16:00',reason:'General check-up',status:'Scheduled'},
 {id:'a6',patientId:'p1',doctorId:'d2',date:'2026-10-06',time:'10:00',reason:'Cardiac screening',status:'Scheduled'},
 {id:'a7',patientId:'p2',doctorId:'d3',date:'2026-10-07',time:'15:00',reason:'Follow-up',status:'Scheduled'}
];
function useStore(key,initial){const [value,setValue]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))??initial}catch{return initial}});useEffect(()=>localStorage.setItem(key,JSON.stringify(value)),[key,value]);return [value,setValue]}
const fmtDate=d=>new Date(d+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const initials=n=>n.split(' ').map(x=>x[0]).join('').slice(0,2);
function App(){const [doctors,setDoctors]=useStore('careflow_doctors',seedDoctors);const [patients,setPatients]=useStore('careflow_patients',seedPatients);const [appointments,setAppointments]=useStore('careflow_appointments',seedAppointments);const [sidebar,setSidebar]=useState(false);const [modal,setModal]=useState(null);const [editing,setEditing]=useState(null);const location=useLocation();const path=location.pathname;
 const todayAppts=appointments.filter(a=>a.date===today).sort((a,b)=>a.time.localeCompare(b.time));
 const stats={today:todayAppts.length,completed:appointments.filter(a=>a.status==='Completed').length,pending:appointments.filter(a=>['Scheduled','Confirmed'].includes(a.status)).length,patients:patients.length};
 const saveAppointment=(data)=>{if(editing)setAppointments(v=>v.map(a=>a.id===editing.id?{...a,...data}:a));else setAppointments(v=>[...v,{...data,id:'a'+Date.now()}]);setModal(null);setEditing(null)};
 const deleteAppointment=id=>{if(confirm('Delete this appointment?'))setAppointments(v=>v.filter(a=>a.id!==id))};
 const updateStatus=(id,status)=>setAppointments(v=>v.map(a=>a.id===id?{...a,status}:a));
 const addPatient=p=>setPatients(v=>[...v,{...p,id:'p'+Date.now(),lastVisit:today}]);
 const deletePatient=id=>{if(confirm('Delete patient and their appointment history?')){setPatients(v=>v.filter(p=>p.id!==id));setAppointments(v=>v.filter(a=>a.patientId!==id))}};
 const pageTitle=path==='/patients'?'Patients':path==='/doctors'?'Doctors':path==='/appointments'?'Appointments':path==='/calendar'?'Calendar':'Dashboard';
 return <div className="app"><aside className={sidebar?'sidebar open':'sidebar'}><div className="brand"><div className="logo"><HeartPulse size={21}/></div><div><b>CareFlow</b><small>Clinic Planner</small></div><button className="mobile-close" onClick={()=>setSidebar(false)}><X/></button></div><nav><NavLink to="/" end onClick={()=>setSidebar(false)}><LayoutDashboard/>Dashboard</NavLink><NavLink to="/appointments" onClick={()=>setSidebar(false)}><CalendarDays/>Appointments</NavLink><NavLink to="/patients" onClick={()=>setSidebar(false)}><Users/>Patients</NavLink><NavLink to="/doctors" onClick={()=>setSidebar(false)}><Stethoscope/>Doctors</NavLink><NavLink to="/calendar" onClick={()=>setSidebar(false)}><ClipboardList/>Calendar</NavLink></nav><div className="side-card"><div className="mini-icon"><Activity size={18}/></div><b>Clinic status</b><span><i/> All systems operational</span></div><div className="profile"><div className="avatar">AD</div><div><b>Admin Desk</b><small>Reception</small></div><LogOut size={17}/></div></aside><main className="main"><header><button className="hamb" onClick={()=>setSidebar(true)}><Menu/></button><div><span className="eyebrow">OUTPATIENT CLINIC</span><h1>{pageTitle}</h1></div><div className="header-actions"><button className="icon-btn"><Bell size={19}/><span className="dot"/></button><button className="primary" onClick={()=>{setEditing(null);setModal('appointment')}}><Plus size={18}/> New appointment</button></div></header><div className="content">{path==='/'?<Dashboard stats={stats} appointments={appointments} doctors={doctors} patients={patients} onStatus={updateStatus} onNew={()=>setModal('appointment')}/>:path==='/appointments'?<Appointments appointments={appointments} patients={patients} doctors={doctors} onStatus={updateStatus} onEdit={a=>{setEditing(a);setModal('appointment')}} onDelete={deleteAppointment} onNew={()=>{setEditing(null);setModal('appointment')}}/>:path==='/patients'?<Patients patients={patients} appointments={appointments} onAdd={()=>setModal('patient')} onDelete={deletePatient}/>:path==='/doctors'?<Doctors doctors={doctors}/>:<CalendarPage appointments={appointments} patients={patients} doctors={doctors} onEdit={a=>{setEditing(a);setModal('appointment')}}/>}</div></main>{modal==='appointment'&&<AppointmentModal patients={patients} doctors={doctors} initial={editing} appointments={appointments} onClose={()=>{setModal(null);setEditing(null)}} onSave={saveAppointment}/>} {modal==='patient'&&<PatientModal onClose={()=>setModal(null)} onSave={p=>{addPatient(p);setModal(null)}}/>}</div>}
function Dashboard({stats,appointments,doctors,patients,onStatus,onNew}){const upcoming=appointments.filter(a=>a.date>=today).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,5);const data=doctors.map(d=>({name:d.name.split(' ').slice(-1)[0],appointments:appointments.filter(a=>a.doctorId===d.id).length}));return <><section className="welcome"><div><p className="muted">Monday, 05 October 2026</p><h2>Good afternoon, Admin.</h2><p>Here’s what’s happening at the clinic today.</p></div><button className="secondary" onClick={onNew}><Plus size={17}/> Schedule visit</button></section><div className="stats">{[['Today’s appointments',stats.today,CalendarDays,'blue'],['Completed',stats.completed,CheckCircle2,'green'],['Pending',stats.pending,Clock3,'amber'],['Total patients',stats.patients,Users,'purple']].map(([t,n,I,c])=><div className="stat" key={t}><div className={'stat-icon '+c}><I size={20}/></div><div><span>{t}</span><strong>{n}</strong></div><TrendingUp className="trend" size={16}/></div>)}</div><div className="grid-2"><section className="panel"><div className="panel-head"><div><h3>Upcoming appointments</h3><p>Next scheduled patient visits</p></div><NavLink className="text-link" to="/appointments">View all</NavLink></div><div className="appointment-list">{upcoming.map(a=><AppointmentRow key={a.id} a={a} patients={patients} doctors={doctors} onStatus={onStatus}/>)}{!upcoming.length&&<Empty/>}</div></section><section className="panel chart-panel"><div className="panel-head"><div><h3>Appointments by doctor</h3><p>Current appointment load</p></div></div><ResponsiveContainer width="100%" height={230}><BarChart data={data} margin={{top:10,right:10,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:12}}/><YAxis allowDecimals={false} tick={{fontSize:12}}/><Tooltip/><Bar dataKey="appointments" radius={[6,6,0,0]} fill="#4f46e5"/></BarChart></ResponsiveContainer></section></div><section className="panel quick"><div className="panel-head"><div><h3>Quick actions</h3><p>Common front-desk tasks</p></div></div><div className="quick-grid"><button onClick={onNew}><CalendarDays/><span><b>Book appointment</b><small>Create a new patient visit</small></span></button><NavLink to="/patients"><Users/><span><b>Manage patients</b><small>View patient records</small></span></NavLink><NavLink to="/doctors"><Stethoscope/><span><b>View doctors</b><small>Check availability</small></span></NavLink></div></section></>}
function AppointmentRow({a,patients,doctors,onStatus}){const p=patients.find(x=>x.id===a.patientId),d=doctors.find(x=>x.id===a.doctorId);return <div className="appt-row"><div className="time"><b>{a.time}</b><span>{a.date===today?'Today':fmtDate(a.date)}</span></div><div className="patient-avatar">{initials(p?.name||'NA')}</div><div className="appt-info"><b>{p?.name||'Unknown patient'}</b><span>{d?.name} · {d?.specialty}</span></div><span className={'status '+a.status.toLowerCase()}>{a.status}</span><button className="tiny-select" onClick={()=>onStatus(a.id,a.status==='Completed'?'Confirmed':'Completed')}>{a.status==='Completed'?'Reopen':'Complete'}</button></div>}
function Appointments({appointments,patients,doctors,onStatus,onEdit,onDelete,onNew}){const [q,setQ]=useState('');const [filter,setFilter]=useState('All');const list=appointments.filter(a=>{const p=patients.find(x=>x.id===a.patientId);return (filter==='All'||a.status===filter)&&((p?.name||'').toLowerCase().includes(q.toLowerCase())||a.reason.toLowerCase().includes(q.toLowerCase()))}).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));return <><section className="toolbar"><div><h2>Appointments</h2><p>Plan and manage all outpatient visits.</p></div><button className="primary" onClick={onNew}><Plus size={18}/> New appointment</button></section><div className="filters"><div className="search"><Search size={18}/><input placeholder="Search patient or reason..." value={q} onChange={e=>setQ(e.target.value)}/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Scheduled</option><option>Confirmed</option><option>Completed</option><option>Cancelled</option></select></div><section className="panel table-panel"><table><thead><tr><th>Date & time</th><th>Patient</th><th>Doctor</th><th>Reason</th><th>Status</th><th>Actions</th></tr></thead><tbody>{list.map(a=>{const p=patients.find(x=>x.id===a.patientId),d=doctors.find(x=>x.id===a.doctorId);return <tr key={a.id}><td><b>{fmtDate(a.date)}</b><span>{a.time}</span></td><td><div className="cell-person"><div className="patient-avatar">{initials(p?.name||'NA')}</div>{p?.name}</div></td><td>{d?.name}<span>{d?.specialty}</span></td><td>{a.reason}</td><td><span className={'status '+a.status.toLowerCase()}>{a.status}</span></td><td><div className="row-actions"><button onClick={()=>onEdit(a)} title="Edit"><Edit3 size={16}/></button><button onClick={()=>onDelete(a.id)} title="Delete"><Trash2 size={16}/></button></div></td></tr>})}</tbody></table>{!list.length&&<Empty/>}</section></>}
function Patients({patients,appointments,onAdd,onDelete}){return <><section className="toolbar"><div><h2>Patients</h2><p>Patient directory and visit history.</p></div><button className="primary" onClick={onAdd}><Plus size={18}/> Add patient</button></section><div className="patient-grid">{patients.map(p=><div className="patient-card" key={p.id}><div className="card-top"><div className="large-avatar">{initials(p.name)}</div><button className="more"><MoreHorizontal size={19}/></button></div><h3>{p.name}</h3><p>{p.age} years · {p.gender}</p><div className="contact"><span>{p.phone}</span><span>Last visit: {fmtDate(p.lastVisit)}</span></div><div className="card-foot"><span><CalendarDays size={15}/> {appointments.filter(a=>a.patientId===p.id).length} appointments</span><button onClick={()=>onDelete(p.id)}><Trash2 size={15}/></button></div></div>)}</div></>}
function Doctors({doctors}){return <><section className="toolbar"><div><h2>Doctors</h2><p>Clinician profiles and weekly availability.</p></div></section><div className="doctor-grid">{doctors.map(d=><div className="doctor-card" key={d.id}><div className="doctor-head"><div className="doctor-avatar" style={{background:d.color}}><Stethoscope size={23}/></div><span className="available"><i/> Available</span></div><h3>{d.name}</h3><p>{d.specialty}</p><div className="doctor-meta"><span>Room {d.room}</span><span>₹{d.fee} / visit</span></div><div className="days"><small>Weekly schedule</small><div>{d.days.map(x=><b key={x}>{x}</b>)}</div></div></div>)}</div></>}
function CalendarPage({appointments,patients,doctors,onEdit}){const [date,setDate]=useState(today);const list=appointments.filter(a=>a.date===date).sort((a,b)=>a.time.localeCompare(b.time));return <><section className="toolbar"><div><h2>Calendar</h2><p>Daily appointment schedule.</p></div><div className="date-nav"><button onClick={()=>setDate(shiftDate(date,-1))}><ChevronLeft/></button><b>{fmtDate(date)}</b><button onClick={()=>setDate(shiftDate(date,1))}><ChevronRight/></button></div></section><section className="calendar"><div className="day-label"><CalendarDays size={19}/><b>{date===today?'Today':fmtDate(date)}</b><span>{list.length} visits</span></div>{list.length?list.map(a=>{const p=patients.find(x=>x.id===a.patientId),d=doctors.find(x=>x.id===a.doctorId);return <div className="timeline" key={a.id}><div className="timeline-time">{a.time}</div><div className="timeline-line"><i/></div><div className="timeline-card"><div><b>{p?.name}</b><span>{d?.name} · {d?.specialty}</span><small>{a.reason}</small></div><div><span className={'status '+a.status.toLowerCase()}>{a.status}</span><button className="edit-btn" onClick={()=>onEdit(a)}><Edit3 size={15}/> Edit</button></div></div></div>}):<Empty/>}</section></>}
function shiftDate(date,days){const d=new Date(date+'T00:00:00');d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function AppointmentModal({patients,doctors,initial,appointments,onClose,onSave}){const [form,setForm]=useState(initial||{patientId:patients[0]?.id||'',doctorId:doctors[0]?.id||'',date:today,time:'09:00',reason:'General consultation',status:'Scheduled'});const [error,setError]=useState('');const set=(k,v)=>setForm(f=>({...f,[k]:v}));const submit=e=>{e.preventDefault();if(!form.patientId||!form.doctorId||!form.date||!form.time){setError('Please complete all required fields.');return}const conflict=appointments.some(a=>a.id!==initial?.id&&a.doctorId===form.doctorId&&a.date===form.date&&a.time===form.time);if(conflict){setError('That doctor already has an appointment at this time. Choose another slot.');return}onSave(form)};return <Modal title={initial?'Edit appointment':'Schedule appointment'} onClose={onClose}><form onSubmit={submit} className="form"><div className="form-grid"><label>Patient<select value={form.patientId} onChange={e=>set('patientId',e.target.value)}>{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Doctor<select value={form.doctorId} onChange={e=>set('doctorId',e.target.value)}>{doctors.map(d=><option key={d.id} value={d.id}>{d.name} · {d.specialty}</option>)}</select></label><label>Date<input type="date" value={form.date} onChange={e=>set('date',e.target.value)}/></label><label>Time<input type="time" value={form.time} onChange={e=>set('time',e.target.value)}/></label><label className="full">Visit reason<input value={form.reason} onChange={e=>set('reason',e.target.value)} placeholder="e.g. Follow-up consultation"/></label><label>Status<select value={form.status} onChange={e=>set('status',e.target.value)}><option>Scheduled</option><option>Confirmed</option><option>Completed</option><option>Cancelled</option></select></label></div>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">{initial?'Save changes':'Create appointment'}</button></div></form></Modal>}
function PatientModal({onClose,onSave}){const [f,setF]=useState({name:'',phone:'',age:'',gender:'Male'});const set=(k,v)=>setF(x=>({...x,[k]:v}));return <Modal title="Add patient" onClose={onClose}><form className="form" onSubmit={e=>{e.preventDefault();if(f.name&&f.phone&&f.age)onSave({...f,age:Number(f.age)})}}><div className="form-grid"><label className="full">Full name<input required value={f.name} onChange={e=>set('name',e.target.value)} placeholder="Patient name"/></label><label>Phone<input required value={f.phone} onChange={e=>set('phone',e.target.value)} placeholder="10-digit number"/></label><label>Age<input required type="number" min="0" max="120" value={f.age} onChange={e=>set('age',e.target.value)}/></label><label>Gender<select value={f.gender} onChange={e=>set('gender',e.target.value)}><option>Male</option><option>Female</option><option>Other</option></select></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Add patient</button></div></form></Modal>}
function Modal({title,onClose,children}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><div><h2>{title}</h2><p>Enter the details below.</p></div><button onClick={onClose}><X/></button></div>{children}</div></div>}
function Empty(){return <div className="empty"><ClipboardList size={27}/><b>No records found</b><span>Try changing your filters or add a new record.</span></div>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
